import { jsPDF } from 'jspdf'
import { formatDate } from './formatDate'

function downloadFile(filename, content, mimeType) {
  const blob = new Blob([content], { type: mimeType })
  const link = document.createElement('a')
  link.href = URL.createObjectURL(blob)
  link.download = filename
  document.body.appendChild(link)
  link.click()
  link.remove()
}

export function generateTicketPdf(reg = {}) {
  try {
    const doc = new jsPDF({ unit: 'pt', format: 'a4' })
    const w = doc.internal.pageSize.getWidth()
    const left = 40
    let y = 56

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(24)
    doc.text('EventHub Ticket', w / 2, y, { align: 'center' })

    y += 40
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(14)
    doc.text(`Event: ${reg.eventTitle || 'Untitled Event'}`, left, y)
    y += 22
    doc.text(`Ticket ID: ${reg.ticketId || 'N/A'}`, left, y)
    y += 22
    doc.text(`Name: ${reg.name || 'Attendee'}`, left, y)
    y += 22
    doc.text(`Ticket type: ${reg.ticketType || 'General'}`, left, y)
    y += 22
    doc.text(`Price: ${reg.price != null ? reg.price : 'Free'}`, left, y)
    y += 22
    doc.text(`Date: ${reg.eventDate ? formatDate(reg.eventDate) : 'TBD'}`, left, y)
    y += 22
    doc.text(`Location: ${reg.eventLocation || 'Online / TBD'}`, left, y)
    y += 32

    if (reg.eventDescription) {
      doc.setFontSize(12)
      doc.text(`Details: ${reg.eventDescription}`, left, y, { maxWidth: w - left * 2 })
      y += 36
    }

    doc.setDrawColor(99, 102, 241)
    doc.setLineWidth(1)
    doc.line(left, y, w - left, y)
    y += 20

    doc.setFontSize(12)
    doc.text('Present this ticket at check-in or scan the QR code for entry.', left, y)
    y += 32
    doc.text('Generated by EventHub', left, y)

    const safe = (str = '') => String(str).replace(/[\\/:*?"<>|]/g, '').replace(/\s+/g, '_')
    const filename = `${safe(reg.eventTitle || 'event')}_${safe(reg.ticketId || 'ticket')}.pdf`
    doc.save(filename)
  } catch (err) {
    console.error('generateTicketPdf error', err)
  }
}

export function downloadCalendarInvite(reg = {}) {
  try {
    const eventTitle = reg.eventTitle || 'EventHub Event'
    const start = reg.eventDate ? new Date(reg.eventDate) : new Date()
    const end = new Date(start.getTime() + 1000 * 60 * 60 * 2)
    const formatDateTime = (date) => date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z'
    const description = `Ticket ID: ${reg.ticketId || 'N/A'} - ${reg.ticketType || 'Ticket'}`
    const location = reg.eventLocation || ''
    const uid = `${reg.ticketId || Date.now()}@eventhub`

    const ics = [
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      'PRODID:-//EventHub//EN',
      'METHOD:PUBLISH',
      'BEGIN:VEVENT',
      `UID:${uid}`,
      `DTSTAMP:${formatDateTime(new Date())}`,
      `DTSTART:${formatDateTime(start)}`,
      `DTEND:${formatDateTime(end)}`,
      `SUMMARY:${eventTitle}`,
      `DESCRIPTION:${description}`,
      `LOCATION:${location}`,
      'END:VEVENT',
      'END:VCALENDAR',
    ].join('\r\n')

    const safe = (str = '') => String(str).replace(/[\\/:*?"<>|]/g, '').replace(/\s+/g, '_')
    const filename = `${safe(eventTitle)}.ics`
    downloadFile(filename, ics, 'text/calendar;charset=utf-8;')
  } catch (err) {
    console.error('downloadCalendarInvite error', err)
  }
}

export default {
  generateTicketPdf,
  downloadCalendarInvite,
}
